### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by theodorusclarence** [theodorusclarence/notiolink#22]
- [x] Optional Twitter Config
- [x] Optimize for switching theme
- [x] Pre-built themes
